name: zego_offline_call
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  zego_zim: any
  zego_zpns: any
  zego_callkit: any
  zego_uikit_prebuilt_call: ^4.9.0

  flutter_styled_toast: ^2.1.3
  device_info_plus: any
  shared_preferences: any
  cached_network_image: ^3.3.0
  permission_handler: ^11.0.1
  crypto: ^3.0.3
  flutter_logs: ^2.1.12
  flutter_dialpad:
    path: ./../flutter_dialpad-1.0.5
  zego_callkit_incoming:
    path: ./../zego_callkit_incoming

dependency_overrides:
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  import_sorter: ^4.6.0  # run 'flutter pub run import_sorter:main'

flutter:
  uses-material-design: true
  assets:
    - assets/image/