name: zego_callkit_incoming
description: "A new Flutter project."
version: 0.0.1
homepage:

environment:
  sdk: ">=2.16.2 <4.0.0"
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  import_sorter: ^4.6.0  # run 'flutter pub run import_sorter:main'

flutter:
  plugin:
    platforms:
      android:
        package: com.zego.callkit.zego_callkit_incoming
        pluginClass: ZegoCallkitIncomingPlugin
      ios:
        pluginClass: ZegoCallkitIncomingPlugin
